<template>
  <LegalPage title="Terms of Service" updated="May 31, 2026">
    <p class="callout">ParlayPal provides <strong>data and analytics</strong> about betting markets for entertainment.
      It is not betting, financial, or investment advice, and we do not accept wagers or operate a sportsbook.</p>

    <section>
      <h2>1. Acceptance</h2>
      <p>By accessing or using parlaypal.gg ("the Service"), you agree to these Terms. If you do not agree, do not use the Service.</p>
    </section>

    <section>
      <h2>2. What the Service is</h2>
      <p><strong>ParlayPal is an analytics tool.</strong> We analyze publicly available sportsbook odds and surface markets our models judge to be mispriced, along with arbitrage opportunities. Signals are informational and probabilistic - they are not a promise of profit, and they are not advice to place any particular bet.</p>
    </section>

    <section>
      <h2>3. Age requirement</h2>
      <p>You must be 21 or older (or the legal age in your jurisdiction, whichever is higher) to use the Service. By using it, you represent that you meet this requirement.</p>
    </section>

    <section>
      <h2>4. Responsible gambling</h2>
      <p>Gambling carries real financial risk and can be addictive. Never stake more than you can afford to lose, and treat any stake sizing we suggest as illustrative. If you or someone you know needs help:</p>
      <ul>
        <li><strong>National Problem Gambling Helpline:</strong> 1-800-GAMBLER (1-800-426-2537)</li>
        <li><strong>Online:</strong> <a href="https://www.ncpgambling.org" target="_blank" rel="noopener">ncpgambling.org</a></li>
        <li><strong>Text:</strong> "HELLO" to 741741</li>
      </ul>
    </section>

    <section>
      <h2>5. Subscriptions &amp; billing</h2>
      <p>Paid tiers are billed monthly through Stripe and renew automatically until cancelled. You can cancel anytime, effective at the end of the current billing period. Prices and tier features may change with notice. Except where required by law, payments are non-refundable.</p>
    </section>

    <section>
      <h2>6. No warranty on data or signals</h2>
      <p>Odds and match data come from third-party sources and may be delayed, inaccurate, or unavailable. Signals are generated by our models and may be wrong. We make no warranties - express or implied - about accuracy, availability, or results. Always verify prices directly with your sportsbook. <strong>Past performance does not guarantee future results.</strong></p>
    </section>

    <section>
      <h2>7. Limitation of liability</h2>
      <p>To the fullest extent permitted by law, ParlayPal and its operators are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the Service, including any losses from acting on information it provides.</p>
    </section>

    <section>
      <h2>8. Affiliate disclosure</h2>
      <p>We may participate in affiliate programs with sportsbooks. We may earn a commission when you sign up or deposit through a link we provide. This never affects the signals we surface or our analysis.</p>
    </section>

    <section>
      <h2>9. Third-party links &amp; jurisdiction</h2>
      <p>The Service links to third-party sportsbooks and sites we don't control and don't endorse. Online sports betting is regulated locally - it is your responsibility to ensure it is legal where you are before acting on any information here.</p>
    </section>

    <section>
      <h2>10. Intellectual property</h2>
      <p>All content, models, and design are the property of ParlayPal or its licensors. You may not reproduce, redistribute, or resell the signals or create derivative works without our written permission.</p>
    </section>

    <section>
      <h2>11. Changes &amp; contact</h2>
      <p>We may modify these Terms; changes are effective on posting. Continued use means acceptance. Questions? Email <a href="mailto:carlos@excelsiordevs.com">carlos@excelsiordevs.com</a>.</p>
    </section>
  </LegalPage>
</template>

<script setup lang="ts">
import LegalPage from '../components/LegalPage.vue'
</script>
